# Generated by Django 4.1.1 on 2022-09-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='abcd', max_length=30),
        ),
    ]
